# The URL the site will be built for
base_url = "https://pyjamas.live"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "hyde"
description = "pyjamasconf esta chegando"
title = "Pyjamas Conf"

[extra]
hyde_links = [
    {url = "https://github.com/pyjamasconf/codigo-de-conduta", name = "Código de conduta"},
    {url = "https://github.com/pyjamasconf/", name = "PyjamasConf @ Github"},
]
hyde_sticky = false